
#ifndef VTKFILTERSPARALLELMPI_EXPORT_H
#define VTKFILTERSPARALLELMPI_EXPORT_H

#ifdef VTKFILTERSPARALLELMPI_STATIC_DEFINE
#  define VTKFILTERSPARALLELMPI_EXPORT
#  define VTKFILTERSPARALLELMPI_NO_EXPORT
#else
#  ifndef VTKFILTERSPARALLELMPI_EXPORT
#    ifdef FiltersParallelMPI_EXPORTS
        /* We are building this library */
#      define VTKFILTERSPARALLELMPI_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKFILTERSPARALLELMPI_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKFILTERSPARALLELMPI_NO_EXPORT
#    define VTKFILTERSPARALLELMPI_NO_EXPORT 
#  endif
#endif

#ifndef VTKFILTERSPARALLELMPI_DEPRECATED
#  define VTKFILTERSPARALLELMPI_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKFILTERSPARALLELMPI_DEPRECATED_EXPORT
#  define VTKFILTERSPARALLELMPI_DEPRECATED_EXPORT VTKFILTERSPARALLELMPI_EXPORT VTKFILTERSPARALLELMPI_DEPRECATED
#endif

#ifndef VTKFILTERSPARALLELMPI_DEPRECATED_NO_EXPORT
#  define VTKFILTERSPARALLELMPI_DEPRECATED_NO_EXPORT VTKFILTERSPARALLELMPI_NO_EXPORT VTKFILTERSPARALLELMPI_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKFILTERSPARALLELMPI_NO_DEPRECATED
#    define VTKFILTERSPARALLELMPI_NO_DEPRECATED
#  endif
#endif

#endif /* VTKFILTERSPARALLELMPI_EXPORT_H */
